---
name: 🚀 Release Drafter

tag-template: v$RESOLVED_VERSION
name-template: '🧬 Release $RESOLVED_VERSION'
version-template: $MAJOR.$MINOR.$PATCH
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: '- Nothing changed... weird, right? 🤔'

categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
      - feat
  - title: '🐛 Bug Fixes'
    labels:
      - bug
      - fix
      - hotfix
  - title: '🧰 Maintenance'
    labels:
      - chore
      - refactor
      - deps
  - title: '🧪 Tests'
    labels:
      - test
  - title: '🧠 Documentation'
    labels:
      - docs

exclude-labels:
  - skip-changelog
  - automated

replacers:
  - search: '/@banditctl/g'
    replace: '[@banditctl](https://github.com/banditctl)'

template: |
  ## 🔄 What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/${{GITHUB_REPOSITORY}}/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
