extends: default

rules:
  document-start: enable # Warn if '---' is missing
  truthy:
    allowed-values: ["true", "false"]
  new-line-at-end-of-file: enable
  line-length:
    max: 120 # Or 80, if you want it stricter

ignore: |
  downlint.yml
  ub/workflows/markdown-lint.yml
