---
name: Auto-Merge Changelog PRs

on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]'
    steps:
      - name: Check out PR
        uses: actions/checkout@v4

      - name: Auto-merge PR if only CHANGELOG.md is changed and label is "automated"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const labels = pr.data.labels.map(label => label.name);
            const files = await github.paginate(github.rest.pulls.listFiles, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.data.number,
            });

            const onlyChangelog = files.length === 1 && files[0].filename === 'CHANGELOG.md';
            const hasLabel = labels.includes('automated');
            const isBot = pr.data.user.login === 'github-actions[bot]';

            if (onlyChangelog && hasLabel && isBot) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.data.number,
                merge_method: 'squash',
              });

              console.log(`✅ PR #${pr.data.number} auto-merged successfully.`);
            } else {
              console.log('⏸️ Merge skipped. Conditions not met.');
            }
