name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run markdownlint with custom config
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: .markdownlint.yaml
          globs: '**/*.md'
