---
# Test
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  changelog-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: .github/changelog-config.json
          commitMode: false
          failOnError: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_RELEASES }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
