---
name: Update CHANGELOG on Release

on:
  release:
    types: [published, created, prereleased]
permissions:
  contents: write

jobs:
  sync-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Update CHANGELOG.md
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(changelog): update CHANGELOG for ${{ github.event.release.tag_name }}"
          file_pattern: CHANGELOG.md
