---
name: YAML Lint

on:
  push:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List YAML files (Debug)
        run: find . -name '*.yml' -o -name '*.yaml'

      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yaml
